### ISSUE TITLE
Debtor function update is not working

### ISSUE THREAD

**Issue by TosoftAlmor** [tkjaergaard/Economic-PHP-SDK#18]
In the function create the update function is called with a var and an array return $this->update($number, $data); But the function update only has update($data).

Furthermore looking at the object created in line 483 a lot of data is not picked up due to wrong variables like 'VatZone' => $vat_zone, (should be 'VatZone' => $data['Vatzone'],).

And the call for $params array is empty, should be $data as far as I can see

But after trying to fix these issues I now get an error: Got error 'PHP message: PHP Fatal error: SOAP-ERROR: Encoding: object has no 'Id' property in /Economics/Debtor/Debtor.php on line 507

**Comment by crisbeto** [comment]
I'm also experiencing this issue. It seems that e-conomic renamed some fields, as well as the update method is referring to variables and arguments that aren't there. I'll make a PR for it.

**Comment by piotrpekala** [comment]
When you will make a new release with the deptor fixes? I mean the vatZone and Deoptor update ?

**Comment by redayoub** [comment]
@tkjaergaard I'm having the same issue when I tries to create a new debtor. Could you tell us if this will fixed soo?.

Thanks.

**Comment by tkjaergaard** [comment]
@redayoub I've just merged the PR from @crisbeto. Should be working now.

**Comment by redayoub** [comment]
Thanks @tkjaergaard but I'm still getting this after the update

Fatal error: Class 'tkj\Economics\Debtor\Exception' not found in /var/www/Project/vendor/tkj/economics/src/tkj/Economics/Debtor/Debtor.php on line 513

**Comment by tkjaergaard** [comment]
Ahhh, yeah, I see the bug. I've just removed the try-catch from Debtor.php

**Comment by redayoub** [comment]
Thanks @tkjaergaard

**Comment by redayoub** [comment]
@tkjaergaard according to the doc we can get the debitor number after creation like that:

$debtorNumber = $debtor->create($data);

But in fact the create method returns true after debitor creation. Any help please?

**Comment by tkjaergaard** [comment]
@redayoub Sorry, missed that when resolving some merge conflicts from the PR. It's fixed now.

**Comment by redayoub** [comment]
Thanks @tkjaergaard
